### ISSUE TITLE
Design rate flow

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/rate.eoscostarica.io#2]
A token holder searches a block producer and rates it using the sliders.

**Comment by murillojorge** [comment]
This is my proposal for the general site flow including Ratings.
[EOSRate-UserFlow-01.pdf](https://github.com/eoscostarica/rate.eoscostarica.io/files/2384377/EOSRate-UserFlow-01.pdf)

**Comment by gaboesquivel** [comment]
@murillojorge I think we can close this.  EOS Rate flow was included in the Readme file and we starting to implement it.
