### ISSUE TITLE
prettier and standardjs overlapping ? 

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/rate.eoscostarica.io#29]
we are currently running both on the `yarn lint` command
`pretty-quick . && eslint --fix .` 

If you run them separately they have differences. 
AFAIK prettier doesn't check for best practices in JS and React it only formats text ( alignments, paddings, spacing )

Thoughts ?

**Comment by gaboesquivel** [comment]
After reading https://prettier.io/docs/en/comparison.html I'm convinced they are complementary. You can always use `{/* prettier-ignore */}` if they conflict for some reason. https://prettier.io/docs/en/ignore.html

**Comment by gaboesquivel** [comment]
I think we should remove pretty-quick in that case, however I do believe there are things that pretty-quick formats that standardjs wont

**Comment by kevinwolfcr** [comment]
Another approach is to delegate auto-formatting to prettier and use eslint just for... lint 🤯
