### ISSUE TITLE
Design Layout, Main Screen and Navigation

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/rate.eoscostarica.io#4]

**Comment by murillojorge** [comment]
Prototypes can be found here:
https://zpl.io/2Zz3EOq

**Comment by murillojorge** [comment]
Please checkout the color scheme and sidebar navigation. 
https://scene.zeplin.io/project/5a58ea3341f76658994e000c

**Comment by gaboesquivel** [comment]
Very nice! tks.
