### ISSUE TITLE
Scatter Integration 

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/rate.eoscostarica.io#5]
We are starting with a Mongo DB for persistence, we need to integrate scatter for registering the the votes on chain

**Comment by gaboesquivel** [comment]
some refs

- https://github.com/EOSEssentials/Scatter-Demos 
- https://get-scatter.com/docs/dev/getting-started
- https://github.com/kesar/decentwitter/

**Comment by gaboesquivel** [comment]
I'm starting to work on this one

**Comment by lelui12cr** [comment]
I will add here the different screenshots
